### ISSUE TITLE
Enhancement: Include SSM EC2 Role and SSM Bastion

### ISSUE THREAD

**Issue by kennschr** [aws-samples/aws-vpc-builder-cdk#5]
Immediate first step after deploying VPC builder was to launch a basic instance with SSM connectivity.  Would be nice to bootstrap the IAM Role for EC2 SSM Access and launch a bastion in each VPC as part of initial deploy.

**Comment by apmclean** [comment]
Thanks for the suggestion!  I'm aiming to keep this project focused on VPC / AWS Networking.

Creation of a Bastion host is made fairly straight forward using the CDK.  Consider using this construct: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2.BastionHostLinux.html

Importing the VPC that you've built using this project as a 'destination' for the bastion should be fairly straight forward using the VPC Lookup methods within the CDK: https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-ec2.Vpc.html#static-fromwbrlookupscope-id-options

You could also construct the VPC from attributes using the SSM Parameter outputs this project seeds too!
